USB_VID = 0x239A
USB_PID = 0xF057
USB_PRODUCT = "STM32F429 Discovery Board - CPy"
USB_MANUFACTURER = "STMicroelectronics"

INTERNAL_FLASH_FILESYSTEM = 1

# EXTERNAL_FLASH_DEVICES = 例如支持外部 SPI/QSPI Flash，可开启并指定芯片型号

MCU_SERIES = F4
MCU_VARIANT = STM32F429xx
MCU_PACKAGE = LQFP144

LD_COMMON = boards/common_default.ld
LD_FILE = boards/STM32F429_fs.ld
PERIPHERALS_PATH = stm32f4/stm32f429zi
